#! /usr/bin/perl
#
# Hook for automatic backports.
#
# Target dist: Ubuntu Focal Fossa

use warnings;
use strict;
use Carp;

open(F, "debian/control") or croak;
my $file;
while (<F>) {
  $file .= $_;
}
close(F);

$file .= "\n";

$file =~ s/ice34-slice/zeroc-ice-slice/g;
$file =~ s/ice34-translators/zeroc-ice-compilers/g;
$file =~ s/libzeroc-ice34-dev/libzeroc-ice-dev/g;

open(F, ">debian/control") or croak;
print F $file;
close(F);
