#! /usr/bin/perl
#
# Hook for automatic backports.
#
# Target dist: Ubuntu Precise

use warnings;
use strict;
use Carp;

open(F, "debian/control") or croak;
my $file;
while (<F>) {
  $file .= $_;
}
close(F);

$file =~ s/ice35/ice34/g;
$file =~ s/ libopus-dev,\n//g;

open(F, ">debian/control") or croak;
print F $file;
close(F);

$file = '';
open(F, "debian/rules") or croak;
while (<F>) {
  $file .= $_;
}
close(F);

$file =~ s/CONFIG\*=no-bundled-opus \\/CONFIG*=bundled-opus \\/;

open(F, ">debian/rules") or croak;
print F $file;
close(F);

