#! /usr/bin/perl
#
# Hook for automatic backports.
#
# Target dist: Ubuntu Vivid

use warnings;
use strict;
use Carp;

open(F, "debian/control") or croak;
my $file;
while (<F>) {
  $file .= $_;
}
close(F);

$file =~ s/libzeroc-ice-dev/libzeroc-ice35-dev/g;
$file =~ s/zeroc-ice-compilers/ice35-translators/g;
$file =~ s/zeroc-ice-slice/ice35-slice/g;

open(F, ">debian/control") or croak;
print F $file;
close(F);
